#!/bin/sh

# Clean vim
rm -rf ~/.vim

# Set up plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp -r vimrc ~/.vimrc
