#! /bin/usr/env bash

alias ga="git a"
alias gd="git d"
alias gf="git fetch"
alias grg="git rg"
alias gr="git remote -v"
alias gs="git st --ignore-submodules"
alias gss="git st"

alias re-csh="exec zsh -l"

alias gcd='cd $(git rev-parse --show-toplevel)'

alias rgi="rg --no-ignore"

alias ta="tmux attach"

alias lssize="du -h -d 1 --exclude .snapshot"

alias gitconfig='vim $XDG_CONFIG_HOME/git/config'

alias thist="tmux capture-pane -epS - > /tmp/tmuxhist && vim -c 'te cat /tmp/tmuxhist' -c stopinsert"

alias vim="nvim"
alias vimdiff="nvim -d"

alias utop='top -u $USER'
