#! /bin/usr/env bash

alias ga="git add"
alias gd="git diff"
alias gf="git fetch"
alias gr="git remote -v"
alias gs="git status"

alias re-csh="exec zsh -l"

alias gcd='cd $(git rev-parse --show-toplevel)'

alias rgi="rg --no-ignore"

alias ta="tmux attach"

alias lssize="du -h -d 1 --exclude .snapshot"

alias gitconfig='vim $XDG_CONFIG_HOME/git/config'

alias thist="tmux capture-pane -epS - > /tmp/tmuxhist && vim -c 'te cat /tmp/tmuxhist' -c stopinsert"

alias vim="nvim"

alias utop='top -u $USER'

alias .nv='cd ~/projects/neovim'
alias .dot='cd ~/projects/dotfiles'
